name = "horof-sync"
main = "src/index.js"
compatibility_date = "2026-02-19"

[vars]
ALLOWED_ORIGINS = "https://horof.sandooq-games.com,https://sync.horof.sandooq-games.com"
PUSHER_MESSAGES_LIMIT = "4000000"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]
